version: "3.7"
services:
  api:
    build: .
    ports: 
      - "3000:${PORT}"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MDATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASSWORD}
    expose:
      - "27017"
    volumes:
      - bubble_tea:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MPASSWORD}
    logging:
      driver: none
volumes:
  bubble_tea:

    